name: Run CI tests
on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 2'
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  coverage:
    uses: ./.github/workflows/coverage.yml
  wheels:
    uses: ./.github/workflows/wheels.yml
    needs:
      - coverage
